# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSdnQRvj3GefzpIEIDwOytDghCU4w_Gx
"""

def aholi_soni(davlatlar):
  if davlat=="xitoy":
    return "bir milyartdan oshiq"
  elif davlat=="ozbekiston":
    return "37 milyon"
  elif davlat=="germaniya":
    return "malumot yoq"
davlat=input("davlatni kiriting ")
natija=aholi_soni(davlat)
print(natija)